---
deploy_user: deploy

ssh_public_key: "~/.ssh/id_ed25519.pub"

sdahub_root: /opt/sdahub
compose_dir: "{{ sdahub_root }}/compose"
config_dir: "{{ sdahub_root }}/configs"
data_dir: "{{ sdahub_root }}/data"
backup_dir: "{{ sdahub_root }}/backups"
scripts_dir: "{{ sdahub_root }}/scripts"

portainer_port: 9443
portainer_version: "2.27.9"