---
deploy_user: deploy

ssh_public_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

sdahub_root: /opt/sdahub
compose_dir: "{{ sdahub_root }}/compose"
config_dir: "{{ sdahub_root }}/configs"
data_dir: "{{ sdahub_root }}/data"
backup_dir: "{{ sdahub_root }}/backups"
scripts_dir: "{{ sdahub_root }}/scripts"

# --- Monitoring ---
# Prometheus
prometheus_version: "v3.5.0"

# Node Exporter
node_exporter_version: "v1.9.1"

# Grafana
grafana_enabled: true
grafana_version: "12.2.0"
grafana_admin_user: "admin"
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"

# Домены
domain: sdahub.ru
grafana_subdomain: grafana.{{ domain }}
portainer_subdomain: portainer.{{ domain }}

# Portainer 
portainer_http_port: 9000
portainer_https_port: 9443   
portainer_use_http: true     
portainer_version: "2.27.9"

# Loki
loki_version: "3.5.0"
loki_data_dir: "{{ data_dir }}/loki"

# Promtail
promtail_version: "3.5.0"                 