---
- name: Create deploy user
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    groups:
      - sudo
    append: true
    create_home: true


- name: Add SSH public key for deploy
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', ssh_public_key) }}"


- name: Configure passwordless sudo for deploy
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ deploy_user }}"
    content: |
      {{ deploy_user }} ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: "0440"