---
- name: Deploy docker-compose for node_exporter
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/node_exporter/docker-compose.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0640"

- name: Start node_exporter
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}/node_exporter"
    state: present