---
- name: Create directory for node_exporter compose
  ansible.builtin.file:
    path: "{{ compose_dir }}/node_exporter"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"

- name: Create monitoring network (if not exists)
  community.docker.docker_network:
    name: monitoring
    driver: bridge
    state: present
  become: yes

- name: Deploy docker-compose for node_exporter
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/node_exporter/docker-compose.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"

- name: Reset ssh connection
  ansible.builtin.meta:
    reset_connection

- name: Start node_exporter
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}/node_exporter"
    state: present