---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- import_tasks: packages.yml

- import_tasks: directories.yml

- name: Set custom MOTD
  ansible.builtin.copy:
    dest: /etc/motd
    content: |
      Welcome to SDAHub Platform
      Managed by Ansible
    owner: root
    group: root
    mode: "0644"
