---
- name: Deploy Grafana datasources config
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: "{{ config_dir }}/grafana/datasources.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"

- name: Deploy docker-compose for Grafana
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/grafana/docker-compose.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"

- name: Reset ssh connection
  ansible.builtin.meta:
    reset_connection

- name: Start Grafana
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}/grafana"
    state: present