---

- name: Check if grafana database exists
  stat:
    path: /opt/sdahub/data/grafana/grafana.db
  register: grafana_db

- name: Fix grafana database permissions
  file:
    path: /opt/sdahub/data/grafana/grafana.db
    owner: 472
    group: 472
    mode: "0644"
  when: grafana_db.stat.exists