---
- name: Configure server
  hosts: all
  become: true

  roles:
  - common
  - security
  - docker

  - node_exporter
  - prometheus
  - loki
  - promtail
  - grafana
  - portainer

  - nginx
  - certbot