---
- name: Configure server
  hosts: all
  become: true

  vars_files:
    - ../inventory/group_vars/vault.yml

  roles:
  - common
  - security
  - docker

  - node_exporter
  - prometheus
  - loki
  - promtail
  - grafana
  - portainer

  - nginx
  - certbot

- name: Enable SSL
  hosts: all
  become: true

  roles:
    - nginx_ssl