---
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - containerd.io
      - docker-compose-plugin
    state: present
