---
- name: Enable Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Create monitoring docker network
  community.docker.docker_network:
    name: monitoring
    driver: bridge
    state: present

- name: Add deploy user to docker group
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes