---
- name: Enable Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Add deploy user to docker group
  user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes
