---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present


- name: Create fail2ban local configuration
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
    content: |
      [DEFAULT]
      bantime = 1h
      findtime = 10m
      maxretry = 5
      backend = systemd
      allowipv6 = auto

      [sshd]
      enabled = true
      port = ssh
      logpath = %(sshd_log)s
      maxretry = 3


- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: restarted
  when: ansible_check_mode == false