---
- name: Deploy Loki configuration
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: "{{ config_dir }}/loki/loki-config.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"

- name: Deploy docker-compose for Loki
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/loki/docker-compose.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"

- name: Reset ssh connection
  ansible.builtin.meta:
    reset_connection

- name: Start Loki
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}/loki"
    state: present